2016-05-13T06:12:29.512937+00:00 app[web.1]:     self.callable = self.load()
2016-05-13T06:12:29.512937+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2016-05-13T06:12:29.512942+00:00 app[web.1]:     application = get_wsgi_application()
2016-05-13T06:12:29.512933+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
2016-05-13T06:12:29.512943+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
2016-05-13T06:12:29.512944+00:00 app[web.1]:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2016-05-13T06:12:29.512940+00:00 app[web.1]:     return util.import_app(self.app_uri)
2016-05-13T06:12:29.512938+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2016-05-13T06:12:29.512945+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 55, in __getattr__
2016-05-13T06:12:29.512946+00:00 app[web.1]:     self._setup(name)
2016-05-13T06:12:29.512948+00:00 app[web.1]:     mod = importlib.import_module(self.SETTINGS_MODULE)
2016-05-13T06:12:29.512947+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 99, in __init__
2016-05-13T06:12:29.512949+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
2016-05-13T06:12:29.512942+00:00 app[web.1]:   File "/app/AIRPACT_Fire/wsgi.py", line 18, in <module>
2016-05-13T06:12:29.512947+00:00 app[web.1]:     self._wrapped = Settings(settings_module)
2016-05-13T06:12:29.512958+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
2016-05-13T06:12:29.512955+00:00 app[web.1]:    [2016-05-13 06:12:29 +0000] [9] [ERROR] Exception in worker process:
2016-05-13T06:12:29.512957+00:00 app[web.1]:     worker.init_process()
2016-05-13T06:12:29.512956+00:00 app[web.1]: Traceback (most recent call last):
2016-05-13T06:12:29.512943+00:00 app[web.1]:     django.setup()
2016-05-13T06:12:29.512959+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
2016-05-13T06:12:29.512946+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 43, in _setup
2016-05-13T06:12:29.512944+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/__init__.py", line 17, in setup
2016-05-13T06:12:29.512959+00:00 app[web.1]:     self.load_wsgi()
2016-05-13T06:12:29.512966+00:00 app[web.1]:     application = get_wsgi_application()
2016-05-13T06:12:29.512957+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
2016-05-13T06:12:29.512960+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2016-05-13T06:12:29.512969+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 55, in __getattr__
2016-05-13T06:12:29.512965+00:00 app[web.1]:     __import__(module)
2016-05-13T06:12:29.512963+00:00 app[web.1]:     return util.import_app(self.app_uri)
2016-05-13T06:12:29.512963+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2016-05-13T06:12:29.512964+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
2016-05-13T06:12:29.512988+00:00 app[web.1]:     self._setup(name)
2016-05-13T06:12:29.512990+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 43, in _setup
2016-05-13T06:12:29.512990+00:00 app[web.1]:     self._wrapped = Settings(settings_module)
2016-05-13T06:12:29.512991+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 99, in __init__
2016-05-13T06:12:29.512965+00:00 app[web.1]:   File "/app/AIRPACT_Fire/wsgi.py", line 18, in <module>
2016-05-13T06:12:29.512992+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
2016-05-13T06:12:29.512967+00:00 app[web.1]:     django.setup()
2016-05-13T06:12:29.512991+00:00 app[web.1]:     mod = importlib.import_module(self.SETTINGS_MODULE)
2016-05-13T06:12:29.512961+00:00 app[web.1]:     self.callable = self.load()
2016-05-13T06:12:29.512993+00:00 app[web.1]:   File "/app/AIRPACT_Fire/settings.py", line 166, in <module>
2016-05-13T06:12:29.512968+00:00 app[web.1]:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2016-05-13T06:12:29.512994+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/UserDict.py", line 40, in __getitem__
2016-05-13T06:12:29.512961+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2016-05-13T06:12:29.512995+00:00 app[web.1]: KeyError: 'AWS_ACCESS_KEY_ID'
2016-05-13T06:12:29.512992+00:00 app[web.1]:     __import__(name)
2016-05-13T06:12:29.512993+00:00 app[web.1]:     AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
2016-05-13T06:12:29.512996+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
2016-05-13T06:12:29.512997+00:00 app[web.1]:     worker.init_process()
2016-05-13T06:12:29.512998+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
2016-05-13T06:12:29.512998+00:00 app[web.1]:     self.load_wsgi()
2016-05-13T06:12:29.513001+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2016-05-13T06:12:29.513002+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2016-05-13T06:12:29.513002+00:00 app[web.1]:     return util.import_app(self.app_uri)
2016-05-13T06:12:29.513001+00:00 app[web.1]:     return self.load_wsgiapp()
2016-05-13T06:12:29.513000+00:00 app[web.1]:     self.callable = self.load()
2016-05-13T06:12:29.513003+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
2016-05-13T06:12:29.512966+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
2016-05-13T06:12:29.513009+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 99, in __init__
2016-05-13T06:12:29.513005+00:00 app[web.1]:     django.setup()
2016-05-13T06:12:29.513082+00:00 app[web.1]:   File "/app/AIRPACT_Fire/settings.py", line 166, in <module>
2016-05-13T06:12:29.512996+00:00 app[web.1]: Traceback (most recent call last):
2016-05-13T06:12:29.513009+00:00 app[web.1]:     self._wrapped = Settings(settings_module)
2016-05-13T06:12:29.512962+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2016-05-13T06:12:29.513085+00:00 app[web.1]:   File "/app/AIRPACT_Fire/settings.py", line 166, in <module>
2016-05-13T06:12:29.512994+00:00 app[web.1]:     raise KeyError(key)
2016-05-13T06:12:29.512999+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2016-05-13T06:12:29.513084+00:00 app[web.1]: __import__(name)
2016-05-13T06:12:29.512997+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
2016-05-13T06:12:29.513080+00:00 app[web.1]:      __import__(name)
2016-05-13T06:12:29.513004+00:00 app[web.1]:     application = get_wsgi_application()
2016-05-13T06:12:29.513007+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 55, in __getattr__
2016-05-13T06:12:29.513083+00:00 app[web.1]:     raise KeyError(key)
2016-05-13T06:12:29.513007+00:00 app[web.1]:     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
2016-05-13T06:12:29.513008+00:00 app[web.1]:     self._setup(name)
2016-05-13T06:12:29.513085+00:00 app[web.1]:     AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
2016-05-13T06:12:29.513252+00:00 app[web.1]: [2016-05-13 06:12:29 +0000] [9] [INFO] Worker exiting (pid: 9)
2016-05-13T06:12:29.513010+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_module
2016-05-13T06:12:29.513084+00:00 app[web.1]: KeyError: 'AWS_ACCESS_KEY_ID'
2016-05-13T06:12:29.646205+00:00 heroku[web.1]: State changed from starting to up
2016-05-13T06:12:29.513419+00:00 app[web.1]: [2016-05-13 06:12:29 +0000] [10] [INFO] Worker exiting (pid: 10)
2016-05-13T06:12:29.513087+00:00 app[web.1]: KeyError: 'AWS_ACCESS_KEY_ID'
2016-05-13T06:12:29.513003+00:00 app[web.1]:     __import__(module)
2016-05-13T06:12:29.512962+00:00 app[web.1]:     return self.load_wsgiapp()
2016-05-13T06:12:29.512999+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2016-05-13T06:12:29.513004+00:00 app[web.1]:   File "/app/AIRPACT_Fire/wsgi.py", line 18, in <module>
2016-05-13T06:12:29.513082+00:00 app[web.1]:     AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
2016-05-13T06:12:29.512968+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/__init__.py", line 17, in setup
2016-05-13T06:12:29.513086+00:00 app[web.1]:     raise KeyError(key)
2016-05-13T06:12:29.513006+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/__init__.py", line 17, in setup
2016-05-13T06:12:29.513008+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/conf/__init__.py", line 43, in _setup
2016-05-13T06:12:29.513005+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
2016-05-13T06:12:29.513010+00:00 app[web.1]:     mod = importlib.import_module(self.SETTINGS_MODULE)
2016-05-13T06:12:29.513083+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/UserDict.py", line 40, in __getitem__
2016-05-13T06:12:29.513086+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/UserDict.py", line 40, in __getitem__
2016-05-13T06:12:59.637384+00:00 app[web.1]: [2016-05-13 06:12:59 +0000] [3] [INFO] Shutting down: Master
2016-05-13T06:12:59.637462+00:00 app[web.1]: [2016-05-13 06:12:59 +0000] [3] [INFO] Reason: Worker failed to boot.
2016-05-13T06:12:59.648777+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=GET path="/" host=dry-harbor-33710.herokuapp.com request_id=0bb8f488-f7a8-404b-8da2-64100d8dd310 fwd="76.178.152.115" dyno=web.1 connect=3ms service=11614ms status=503 bytes=0
2016-05-13T06:13:00.382552+00:00 heroku[web.1]: State changed from up to crashed
2016-05-13T06:13:00.343799+00:00 heroku[web.1]: Process exited with status 3
